### PR TITLE
cli uses ethers v6 version of sdk and local

### PR DESCRIPTION
**Pull request by joewagner**

### CODE REVIEW

**Comment by dtbuchholz** [comment]
@joewagner nre just flagging some stuff that i have here https://github.com/tablelandnetwork/studio/pull/261. i can rebase and whatnot...

**Comment by joewagner** [comment]
> @joewagner nre just flagging some stuff that i have here #261. i can rebase and whatnot...

#261 looks great.  I just merged it here.

**Comment by dtbuchholz** [comment]
@joewagner cool, thanks. and a couple of other things outstanding:
- for some reason, the preview/live version is unable to store table definitions, but the local setup works fine. this is what happens when i try to save a table definition in the UI: `Failed to load resource: the server responded with a status of 500 ()` and states this in the UI: `Error saving def record.`
- if working locally, hardhat will log errors for `RPC Error: The method "eth_maxPriorityFeePerGas" does not exist / is not available` via the new SDK's `getFeeData`. it doesn't have an impact on anything since errors are handled accordingly in that method. Filecoin Calibration does this too, even though [it's a supported method](https://docs.filecoin.io/reference/json-rpc/eth#ethmaxpriorityfeepergas).
- when running locally via `dev:all`, i can create a table on a live chain like Filecoin Calibration. however, for some reason, trying to deploy to Local Tableland is falling. some quick google searches describe the issue comes from a browser wallet connection(?).
```
ALL_ERROR: could not coalesce error (error={ "code": -32603, "message": "Internal JSON-RPC error." }, payload={ "id": 10, "jsonrpc": "2.0", "method": "eth_sendTransaction", "params": [ { "data": "0xa15ab08d00000000000000000000000070997970c51812dc3a010c7d01b50e0d17dc79c800000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000025637265617465207461626c6520746573745f33313333372028696420696e7465676572293b000000000000000000000000000000000000000000000000000000", "from": "0x70997970c51812dc3a010c7d01b50e0d17dc79c8", "gas": "0x14e76", "maxFeePerGas": "0x3b9aca0e", "maxPriorityFeePerGas": "0x3b9aca00", "to": "0xe7f1725e7734ce288f8367e1bb143e90bb3f0512" } ] }, code=UNKNOWN_ERROR, version=6.12.0)
```

**Comment by dtbuchholz** [comment]
(and i forgot to push small cleanups for comments that shouldn't be there. just pushed that directly.)

**Comment by joewagner** [comment]
Looks like hardhat doesn't support `eth_maxPriorityFeePerGas` https://github.com/NomicFoundation/hardhat/issues/1664

**Comment by dtbuchholz** [comment]
> > (and i forgot to push small cleanups for comments that shouldn't be there. just pushed that directly.)
> 
> perfect! Can I rebase this on the newest staging without messing up your local branch?

i actually just pushed that to _this_ branch (instead of #261) with [this commit here](https://github.com/tablelandnetwork/studio/pull/260/commits/6403c78d60be17d9b3657fb0a7364cbc654f4051)...but if that's not ideal, i can create something separate. 

> Looks like hardhat doesn't support `eth_maxPriorityFeePerGas` [NomicFoundation/hardhat#1664](https://github.com/NomicFoundation/hardhat/issues/1664)

ah kk...I'll just make a quick change in the SDK v7 PR and catch hardhat/calibration when trying to call that method

**Comment by joewagner** [comment]
> > perfect! Can I rebase this on the newest staging without messing up your local branch?
> 
> i actually just pushed that to _this_ branch (instead of #261) with [this commit here](https://github.com/tablelandnetwork/studio/pull/260/commits/6403c78d60be17d9b3657fb0a7364cbc654f4051)...but if that's not ideal, i can create something separate. it removed an erroneous comment and reverted a commented line of code back to what you originally had there.

I saw that commit, and it looked good. I was just asking in-case you had some wip changes that hadn't made it to github yet.
I rebased so you will need to delete your local `joe/cli-ethers-v6` branch, if you didn't already.

> ah kk...I'll just make a quick change in the SDK v7 PR and catch hardhat/calibration when trying to call that method

Sounds great

**Comment by dtbuchholz** [comment]
@joewagner ahh gotcha, cool. the only thing i have locally is bumping `next`.

oh, and i resolved the problem noted aboe where i couldn't create a table on hardhat. i hadn't reset my MM wallet nonce 🤦

**Pull request closed without merging**
